package com.hitstdio.fhir.server.util;

public enum ValidationErrorType {
	ABSTRACT_CODE_NOT_ALLOWED,
	CODE_NOT_IN_VALUESET,
	GENERAL_ERROR,
	INVALID_CODE,
    INVALID_DISPLAY,
    INVALID_DISPLAY_WARNING,
    INTERNAL_ERROR,
    INACTIVE_CODE_NOT_ALLOWED,
    NO_SYSTEM,
    RELATIVE_SYSTEM_REFERENCE,
    REFERENCED_VALUESET_NOT_FOUND,
    SYSTEM_NOT_FOUND,
    SYSTEM_IS_VALUESET,
    SYSTEM_NOT_ABSOLUTE,
    SYSTEM_VERSION_NOT_FOUND
}
