package com.hitstdio.fhir.server.util;

public enum ValidationErrorType {
	INVALID_CODE,
    INVALID_DISPLAY,
    SYSTEM_NOT_FOUND,
    CODE_NOT_IN_VALUESET,
    ABSTRACT_CODE_NOT_ALLOWED,
    INACTIVE_CODE_NOT_ALLOWED,
    GENERAL_ERROR,
    INTERNAL_ERROR,
    SYSTEM_IS_VALUESET,
    SYSTEM_NOT_ABSOLUTE,
    RELATIVE_SYSTEM_REFERENCE,
    NO_SYSTEM
}
